#!/usr/bin/env bash

# echo "args received by find-images: $@" > $(tty)

dirPath="$1"
if [[ -z "$dirPath" ]] || [[ "$dirPath" == "-"* && ! -d "$dirPath" ]]
then
  dirPath="."
elif [[ -n "$dirPath" && ! -d "$dirPath" ]]
then
  echo "directory does not exist: $dirPath" >&2
  exit 1
else
  shift
fi

# # stackoverflow.com/a/60559975/1995812
# find "$dirPath" "$@" -xtype f |
# file -L --mime-type -f - |
# grep -P '(image|video|pdf)' |
# grep -iPo '^.*(?=:[^:]+$)' |
# sort -t'/' -k1,1 -k2,2 -k3,3 -k4,4 -k5,5 -k6,6 -k7,7

# it's infinitely faster to just check the file extension instead of the mimetype
find "$dirPath" "$@" -xtype f \
  -regextype posix-extended -iregex '.+\.(jpe?g|png|pdf|mpo|bmp|psp|psd|docx?|pptx?|xcf|tiff?|ico|3gp|3g2|avi|mp4|m4v|mpg|mov|wmv|webm|mkv|vob)$' \
  | sort -t'/' -k1,1 -k2,2 -k3,3 -k4,4 -k5,5 -k6,6 -k7,7
